server:
  port: 8082
spring:
  application:
    name: ms-ItauTransacao

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints.web.exposure.include: "*"